<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

# Working with a real world data-set using SQL and Python

Estimated time needed: **30** minutes

## Objectives

After completing this lab you will be able to:

*   Understand the dataset for Chicago Public School level performance
*   Store the dataset in SQLite database.
*   Retrieve metadata about tables and columns and query data from mixed case columns
*   Solve example problems to practice your SQL skills including using built-in database functions

## Chicago Public Schools - Progress Report Cards (2011-2012)

The city of Chicago released a dataset showing all school level performance data used to create School Report Cards for the 2011-2012 school year. The dataset is available from the Chicago Data Portal: [https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

This dataset includes a large number of metrics. Start by familiarizing yourself with the types of metrics in the database: [https://data.cityofchicago.org/api/assets/AAD41A13-BE8A-4E67-B1F5-86E711E09D5F?download=true](https://data.cityofchicago.org/api/assets/AAD41A13-BE8A-4E67-B1F5-86E711E09D5F?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&download=true&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

**NOTE**:

Do not download the dataset directly from City of Chicago portal. Instead download a static copy which is a more database friendly version from this <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">link</a>.

Now review some of its contents.

### Connect to the database

Let us now load the ipython-sql  extension and establish a connection with the database

##### The syntax for connecting to magic sql using sqllite is

  **%sql sqlite://DatabaseName**   
  
where DatabaseName will be your **.db** file

In [1]:
import csv, sqlite3

con = sqlite3.connect("RealWorldData.db")
cur = con.cursor()

In [ ]:
!pip install pandas
!pip install ipython-sql prettytable

import prettytable
prettytable.DEFAULT = 'DEFAULT'

In [ ]:
!pip install ipython-sql
%load_ext sql

In [4]:
%sql sqlite:///RealWorldData.db

### Store the dataset in a Table

##### In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet.  
##### To analyze the data using SQL, it first needs to be stored in the database.

##### We will first read the csv files  from the given url  into pandas dataframes

##### Next we will be using the  df.to_sql() function to convert each csv file  to a table in sqlite  with the csv data loaded in it.

In [18]:
import pandas as pd
df = pandas.read_csv('Chicago_Public_Schools_-_Progress_Report_Cards__2011-2012__20250426.csv')
df

,School ID,Name of School,"Elementary, Middle, or High School",Street Address,City,State,ZIP Code,Phone Number,Link,Network Manager,...,RCDTS Code,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,Community Area Number,Community Area Name,Ward,Police District,Location
0,609966,Charles G Hammond Elementary School,ES,2819 W 21st Pl,Chicago,IL,60623,(773) 535-4580,http://schoolreports.cps.edu/SchoolProgressRep...,Pilsen-Little Village Elementary Network,...,150000000000000,1157809.015,1889554.623,41.852691,-87.696278,30,SOUTH LAWNDALE,12,10,"(41.85269133, -87.69627777)"
1,610539,Marvin Camras Elementary School,ES,3000 N Mango Ave,Chicago,IL,60634,(773) 534-2960,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,150000000000000,1137482.296,1919394.900,41.934966,-87.770165,19,BELMONT CRAGIN,30,25,"(41.93496641, -87.77016525)"
2,609852,Eliza Chappell Elementary School,ES,2135 W Foster Ave,Chicago,IL,60625,(773) 534-2390,http://schoolreports.cps.edu/SchoolProgressRep...,Ravenswood-Ridge Elementary Network,...,150000000000000,1161016.902,1934466.545,41.975867,-87.683254,4,LINCOLN SQUARE,47,20,"(41.975867, -87.68325438)"
3,609835,Daniel R Cameron Elementary School,ES,1234 N Monticello Ave,Chicago,IL,60651,(773) 534-4290,http://schoolreports.cps.edu/SchoolProgressRep...,Garfield-Humboldt Elementary Network,...,150000000000000,1151767.546,1908130.068,41.903785,-87.717963,23,HUMBOLDT PARK,26,25,"(41.90378521, -87.71796315)"
4,610521,Sir Miles Davis Magnet Elementary Academy,ES,6730 S Paulina St,Chicago,IL,60636,(773) 535-9120,http://schoolreports.cps.edu/SchoolProgressRep...,Englewood-Gresham Elementary Network,...,150000000000000,1166133.893,1859929.018,41.771222,-87.666567,67,WEST ENGLEWOOD,15,7,"(41.77122181, -87.66656657)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561,610506,TEAM Englewood Community Academy High School,HS,6201 S Stewart Ave,Chicago,IL,60621,(773) 535-3530,http://schoolreports.cps.edu/SchoolProgressRep...,Southwest Side High School Network,...,150000000000000,1174730.350,1863740.125,41.781493,-87.634942,68,ENGLEWOOD,20,7,"(41.7814927, -87.63494163)"
562,610350,Robert A Black Magnet Elementary School,ES,9101 S Euclid Ave,Chicago,IL,60619,(773) 535-6390,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,150000000000000,1190807.321,1844986.038,41.729656,-87.576605,48,CALUMET HEIGHTS,8,4,"(41.72965645, -87.57660534)"
563,610154,Martin A Ryerson Elementary School,ES,646 N Lawndale Ave,Chicago,IL,60624,(773) 534-6700,http://schoolreports.cps.edu/SchoolProgressRep...,Garfield-Humboldt Elementary Network,...,150000000000000,1151558.259,1904275.283,41.893211,-87.718833,23,HUMBOLDT PARK,27,11,"(41.89321142, -87.71883334)"
564,610384,Infinity Math Science and Technology High School,HS,3120 S Kostner Ave,Chicago,IL,60623,(773) 535-4225,http://schoolreports.cps.edu/SchoolProgressRep...,West Side High School Network,...,150000000000000,1147521.302,1883405.128,41.836020,-87.734195,30,SOUTH LAWNDALE,22,10,"(41.83601953, -87.73419465)"
565,609870,Daniel J Corkery Elementary School,ES,2510 S Kildare Ave,Chicago,IL,60623,(773) 534-1650,http://schoolreports.cps.edu/SchoolProgressRep...,Pilsen-Little Village Elementary Network,...,150000000000000,1148304.879,1886901.414,41.845599,-87.731229,30,SOUTH LAWNDALE,22,10,"(41.84559878, -87.73122946)"

In [19]:
df.describe()

,School ID,ZIP Code,Safety Score,Environment Score,Instruction Score,Average Student Attendance,Rate of Misconducts (per 100 students),Average Teacher Attendance,Individualized Education Program Compliance Rate,ISAT Exceeding Math %,...,College Enrollment (number of students),General Services Route,RCDTS Code,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,Community Area Number,Ward,Police District
count,566.000000,566.000000,513.000000,513.000000,513.000000,565.000000,566.000000,566.000000,566.000000,476.000000,...,566.000000,566.000000,5.660000e+02,5.660000e+02,5.660000e+02,566.000000,566.000000,566.000000,566.000000,566.000000
mean,609681.791519,60629.727915,49.504873,47.766082,48.288499,92.313805,21.085866,94.378445,98.915371,20.356303,...,626.053004,39.084806,1.500000e+14,1.163016e+06,1.885663e+06,41.841890,-87.677323,37.706714,22.060071,11.710247
std,8831.060946,20.248024,20.110837,16.215584,17.417176,5.993053,27.543835,11.353180,2.311631,16.850870,...,448.495105,6.165552,0.000000e+00,1.605930e+04,3.285688e+04,0.090361,0.058390,21.584135,13.645574,6.688582
min,400018.000000,60605.000000,1.000000,1.000000,1.000000,57.900000,0.000000,0.000000,72.700000,0.000000,...,21.000000,29.000000,1.500000e+14,1.118114e+06,1.817242e+06,41.653674,-87.841052,1.000000,1.000000,1.000000
25%,609873.250000,60618.000000,35.000000,37.000000,37.000000,91.900000,4.525000,95.100000,98.600000,9.175000,...,342.250000,34.000000,1.500000e+14,1.152166e+06,1.860248e+06,41.771866,-87.717152,23.000000,10.000000,7.000000
50%,610052.500000,60625.000000,48.000000,47.000000,47.000000,94.400000,12.250000,95.800000,100.000000,16.000000,...,504.000000,39.000000,1.500000e+14,1.163553e+06,1.886889e+06,41.845521,-87.675878,31.500000,21.000000,10.000000
75%,610212.750000,60639.000000,61.000000,58.000000,59.000000,95.600000,26.975000,96.400000,100.000000,24.900000,...,790.500000,45.000000,1.500000e+14,1.174256e+06,1.911652e+06,41.913584,-87.636059,58.000000,32.750000,17.000000
max,610544.000000,60827.000000,99.000000,99.000000,99.000000,98.400000,251.600000,98.500000,100.000000,100.000000,...,4368.000000,49.000000,1.500000e+14,1.202811e+06,1.950960e+06,42.021064,-87.533007,77.000000,50.000000,25.000000

In [20]:
df.to_sql("schools", con, if_exists='replace', index=False, method="multi")

566

Double-click **here** for the solution.
<!--

import pandas

df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv")
df.to_sql("CHICAGO_PUBLIC_SCHOOLS_DATA", con, if_exists='replace', index=False, method="multi")

-->

### Query the database system catalog to retrieve table metadata

##### You can verify that the table creation was successful by retrieving the list of all tables in your schema and checking whether the SCHOOLS table was created

In [25]:
# type in your query to retrieve list of all tables in the database
%sql SELECT * FROM sqlite_master WHERE type = 'table'

 * sqlite:///RealWorldData.db
Done.

[('table', 'schools', 'schools', 2, 'CREATE TABLE "schools" (\n"School ID" INTEGER,\n  "Name of School" TEXT,\n  "Elementary, Middle, or High School" TEXT,\n  "Street Address" TEXT,\n  " ... (2270 characters truncated) ... tude" REAL,\n  "Community Area Number" INTEGER,\n  "Community Area Name" TEXT,\n  "Ward" INTEGER,\n  "Police District" INTEGER,\n  "Location" TEXT\n)')]

Double-click **here** for a hint

<!--
In sqlite the system catalog table called sqlite_master contains the table metadata
-->

Double-click **here** for the solution.

<!-- Solution using SQLite:

%sql SELECT name FROM sqlite_master WHERE type='table'

-->

### Query the database system catalog to retrieve column metadata

##### The SCHOOLS table contains a large number of columns. How many columns does this table have?

In [29]:
# type in your query to retrieve the number of columns in the SCHOOLS table
%sql SELECT count(name) FROM PRAGMA_table_info('schools')

 * sqlite:///RealWorldData.db
Done.

[(79,)]

Double-click **here** for the solution.

<!-- Solution SQLite:
%sql SELECT count(name) FROM PRAGMA_TABLE_INFO('CHICAGO_PUBLIC_SCHOOLS_DATA');

-->

Now retrieve the the list of columns in SCHOOLS table and their column type (datatype) and length.

In [33]:
# type in your query to retrieve all column names in the SCHOOLS table along with their datatypes and length
%sql SELECT name,type,length(type) FROM PRAGMA_table_info('schools')

 * sqlite:///RealWorldData.db
Done.

[('School ID', 'INTEGER', 7),
 ('Name of School', 'TEXT', 4),
 ('Elementary, Middle, or High School', 'TEXT', 4),
 ('Street Address', 'TEXT', 4),
 ('City', 'TEXT', 4),
 ('State', 'TEXT', 4),
 ('ZIP Code', 'INTEGER', 7),
 ('Phone Number', 'TEXT', 4),
 ('Link ', 'TEXT', 4),
 ('Network Manager', 'TEXT', 4),
 ('Collaborative Name', 'TEXT', 4),
 ('Adequate Yearly Progress Made? ', 'TEXT', 4),
 ('Track Schedule', 'TEXT', 4),
 ('CPS Performance Policy Status', 'TEXT', 4),
 ('CPS Performance Policy Level', 'TEXT', 4),
 ('Healthy Schools Certified?', 'TEXT', 4),
 ('Safety Icon ', 'TEXT', 4),
 ('Safety Score', 'REAL', 4),
 ('Family Involvement Icon', 'TEXT', 4),
 ('Family Involvement Score', 'TEXT', 4),
 ('Environment Icon ', 'TEXT', 4),
 ('Environment Score', 'REAL', 4),
 ('Instruction Icon ', 'TEXT', 4),
 ('Instruction Score', 'REAL', 4),
 ('Leaders Icon ', 'TEXT', 4),
 ('Leaders Score ', 'TEXT', 4),
 ('Teachers Icon ', 'TEXT', 4),
 ('Teachers Score', 'TEXT', 4),
 ('Parent Engagement Icon ', 'TEXT', 4),
 ('Parent Engagement Score', 'TEXT', 4),
 ('Parent Environment Icon', 'TEXT', 4),
 ('Parent Environment Score', 'TEXT', 4),
 ('Average Student Attendance', 'REAL', 4),
 ('Rate of Misconducts (per 100 students) ', 'REAL', 4),
 ('Average Teacher Attendance', 'REAL', 4),
 ('Individualized Education Program Compliance Rate ', 'REAL', 4),
 ('Pk-2 Literacy %', 'TEXT', 4),
 ('Pk-2 Math %', 'TEXT', 4),
 ('Gr3-5 Grade Level Math %', 'TEXT', 4),
 ('Gr3-5 Grade Level Read % ', 'TEXT', 4),
 ('Gr3-5 Keep Pace Read %', 'TEXT', 4),
 ('Gr3-5 Keep Pace Math %', 'TEXT', 4),
 ('Gr6-8 Grade Level Math %', 'TEXT', 4),
 ('Gr6-8 Grade Level Read %', 'TEXT', 4),
 ('Gr6-8 Keep Pace Math%', 'TEXT', 4),
 ('Gr6-8 Keep Pace Read %', 'TEXT', 4),
 ('Gr-8 Explore Math %', 'TEXT', 4),
 ('Gr-8 Explore Read %', 'TEXT', 4),
 ('ISAT Exceeding Math %', 'REAL', 4),
 ('ISAT Exceeding Reading % ', 'REAL', 4),
 ('ISAT Value Add Math', 'REAL', 4),
 ('ISAT Value Add Read', 'REAL', 4),
 ('ISAT Value Add Color Math', 'TEXT', 4),
 ('ISAT Value Add Color Read', 'TEXT', 4),
 ('Students Taking  Algebra %', 'TEXT', 4),
 ('Students Passing  Algebra %', 'TEXT', 4),
 ('9th Grade EXPLORE (2009) ', 'TEXT', 4),
 ('9th Grade EXPLORE (2010) ', 'TEXT', 4),
 ('10th Grade PLAN (2009) ', 'TEXT', 4),
 ('10th Grade PLAN (2010) ', 'TEXT', 4),
 ('Net Change EXPLORE and PLAN', 'TEXT', 4),
 ('11th Grade Average ACT (2011) ', 'TEXT', 4),
 ('Net Change PLAN and ACT', 'TEXT', 4),
 ('College Eligibility %', 'TEXT', 4),
 ('Graduation Rate %', 'TEXT', 4),
 ('College Enrollment Rate %', 'TEXT', 4),
 ('College Enrollment (number of students) ', 'INTEGER', 7),
 ('General Services Route ', 'INTEGER', 7),
 ('Freshman on Track Rate %', 'TEXT', 4),
 ('RCDTS Code', 'INTEGER', 7),
 ('X_COORDINATE', 'REAL', 4),
 ('Y_COORDINATE', 'REAL', 4),
 ('Latitude', 'REAL', 4),
 ('Longitude', 'REAL', 4),
 ('Community Area Number', 'INTEGER', 7),
 ('Community Area Name', 'TEXT', 4),
 ('Ward', 'INTEGER', 7),
 ('Police District', 'INTEGER', 7),
 ('Location', 'TEXT', 4)]

Double-click **here** for the solution.

<!-- Solution 

%sql SELECT name,type,length(type) FROM PRAGMA_TABLE_INFO('CHICAGO_PUBLIC_SCHOOLS_DATA');

-->

### Questions

1.  Is the column name for the "SCHOOL ID" attribute in upper or mixed case?
2.  What is the name of "Community Area Name" column in your table? Does it have spaces?
3.  Are there any columns in whose names the spaces and paranthesis (round brackets) have been replaced by the underscore character "\_"?

## Problems

### Problem 1

##### How many Elementary Schools are in the dataset?

In [34]:
%sql SELECT COUNT( DISTINCT (`School ID`)) From Schools

 * sqlite:///RealWorldData.db
Done.

[(566,)]

Double-click **here** for a hint

<!--
Which column specifies the school type e.g. 'ES', 'MS', 'HS'? ("Elementary School, Middle School, High School")
-->

Double-click **here** for another hint

<!--
Does the column name have mixed case, spaces or other special characters?
If so, ensure you use double quotes around the "Name of the Column"
-->

Double-click **here** for the solution.

<!-- Solution:

%sql select count(*) from CHICAGO_PUBLIC_SCHOOLS_DATA where "Elementary, Middle, or High School"='ES'

Correct answer: 462

-->

### Problem 2

##### What is the highest Safety Score?

In [36]:
%sql SELECT MAX(`Safety Score`) FROM schools

 * sqlite:///RealWorldData.db
Done.

[(99.0,)]

Double-click **here** for a hint

<!--
Use the MAX() function
-->

Double-click **here** for the solution.

<!-- Hint:

%sql select MAX(Safety_Score) AS MAX_SAFETY_SCORE from CHICAGO_PUBLIC_SCHOOLS_DATA

Correct answer: 99
-->

### Problem 3

##### Which schools have highest Safety Score?

In [39]:
%sql SELECT `Name of School` FROM schools WHERE `Safety Score`= (SELECT MAX(`Safety Score`) FROM schools)

 * sqlite:///RealWorldData.db
Done.

[('Abraham Lincoln Elementary School',),
 ('Northside College Preparatory High School',),
 ('Alexander Graham Bell Elementary School',),
 ('Oriole Park Elementary School',),
 ('Mary E Courtenay Elementary Language Arts Center',),
 ('Ellen Mitchell Elementary School',),
 ('Stephen Decatur Classical Elementary School',),
 ('James E McDade Elementary Classical School',),
 ('Norwood Park Elementary School',),
 ('Edgar Allan Poe Elementary Classical School',),
 ('Annie Keller Elementary Gifted Magnet School',),
 ('James G Blaine Elementary School',),
 ('Augustus H Burley Elementary School',),
 ('Talman Elementary School',),
 ('Edgebrook Elementary School',),
 ('Northside Learning Center High School',),
 ('LaSalle Elementary Language Academy',),
 ('Sauganash Elementary School',),
 ('Wildwood Elementary School',)]

Double-click **here** for the solution.

<!-- Solution:
In the previous problem we found out that the highest Safety Score is 99, so we can use that as an input in the where clause:

%sql select Name_of_School, Safety_Score from CHICAGO_PUBLIC_SCHOOLS_DATA where Safety_Score = 99

or, a better way:

%sql select Name_of_School, Safety_Score from CHICAGO_PUBLIC_SCHOOLS_DATA where \
  Safety_Score= (select MAX(Safety_Score) from CHICAGO_PUBLIC_SCHOOLS_DATA)


Correct answer: several schools with with Safety Score of 99.
-->

### Problem 4

##### What are the top 10 schools with the highest "Average Student Attendance"?

In [43]:
%sql SELECT `Name of School`, `Average Student Attendance` FROM schools ORDER BY `Average Student Attendance` DESC LIMIT 10

 * sqlite:///RealWorldData.db
Done.

[('John Charles Haines Elementary School', 98.4),
 ('James Ward Elementary School', 97.8),
 ('Rachel Carson Elementary School', 97.6),
 ('Edgar Allan Poe Elementary Classical School', 97.6),
 ('Orozco Fine Arts & Sciences Elementary School', 97.6),
 ('Annie Keller Elementary Gifted Magnet School', 97.5),
 ('Lenart Elementary Regional Gifted Center', 97.4),
 ('Andrew Jackson Elementary Language Academy', 97.4),
 ('Disney II Magnet School', 97.3),
 ('John H Vanderpoel Elementary Magnet School', 97.2)]

Double-click **here** for the solution.

<!-- Solution:

%sql select Name_of_School, Average_Student_Attendance from CHICAGO_PUBLIC_SCHOOLS_DATA \
    order by Average_Student_Attendance desc nulls last limit 10 

-->

### Problem 5

##### Retrieve the list of 5 Schools with the lowest Average Student Attendance sorted in ascending order based on attendance

In [46]:
%sql SELECT `Name of School`, `Average Student Attendance` \
    FROM schools \
    ORDER BY `Average Student Attendance` \
    LIMIT 5

 * sqlite:///RealWorldData.db
Done.

[('Velma F Thomas Early Childhood Center', None),
 ('Richard T Crane Technical Preparatory High School', 57.9),
 ('Barbara Vick Early Childhood & Family Center', 60.9),
 ('Dyett High School', 62.5),
 ('Wendell Phillips Academy High School', 63.0)]

Double-click **here** for the solution.

<!-- Solution:

%sql SELECT Name_of_School, Average_Student_Attendance  \
     from CHICAGO_PUBLIC_SCHOOLS_DATA \
     order by Average_Student_Attendance \
     LIMIT 5

-->

### Problem 6

##### Now remove the '%' sign from the above result set for Average Student Attendance column

Double-click **here** for a hint

<!--
Use the REPLACE() function to replace '%' with ''

-->

Double-click **here** for the solution.

<!-- Hint:

%sql SELECT Name_of_School, REPLACE(Average_Student_Attendance, '%', '') \
     from CHICAGO_PUBLIC_SCHOOLS_DATA \
     order by Average_Student_Attendance \
     LIMIT 5

-->

### Problem 7

##### Which Schools have Average Student Attendance lower than 70%?

In [47]:
%sql SELECT `Name of School`, `Average Student Attendance` \
    FROM schools \
    WHERE `Average Student Attendance` <= 70

 * sqlite:///RealWorldData.db
Done.

[('Manley Career Academy High School', 66.8),
 ('Dyett High School', 62.5),
 ('Chicago Vocational Career Academy High School', 68.8),
 ('Wendell Phillips Academy High School', 63.0),
 ('Barbara Vick Early Childhood & Family Center', 60.9),
 ('Orr Academy High School', 66.3),
 ('Richard T Crane Technical Preparatory High School', 57.9),
 ('Roberto Clemente Community Academy High School', 69.6)]

Double-click **here** for a hint

<!--
The datatype of the "Average_Student_Attendance" column is varchar.
So you cannot use it as is in the where clause for a numeric comparison.
First use the CAST() function to cast it as a DECIMAL or DOUBLE
e.g. CAST("Column_Name" as DOUBLE)

-->

Double-click **here** for another hint

<!--
Don't forget the '%' age sign needs to be removed before casting
-->

Double-click **here** for the solution.

<!-- Solution:

%sql SELECT Name_of_School, Average_Student_Attendance  \
     from CHICAGO_PUBLIC_SCHOOLS_DATA \
     where CAST ( REPLACE(Average_Student_Attendance, '%', '') AS DOUBLE ) < 70 \
     order by Average_Student_Attendance
     

-->

### Problem 8

##### Get the total College Enrollment for each Community Area

In [69]:
%sql SELECT `Community Area Name`, SUM(`College Enrollment (number of students)	`) \
    FROM Schools	\
    GROUP BY `Community Area Name`

 * sqlite:///RealWorldData.db
Done.

[('ALBANY PARK', 6864),
 ('ARCHER HEIGHTS', 4823),
 ('ARMOUR SQUARE', 1458),
 ('ASHBURN', 6483),
 ('AUBURN GRESHAM', 4175),
 ('AUSTIN', 10933),
 ('AVALON PARK', 1522),
 ('AVONDALE', 3640),
 ('BELMONT CRAGIN', 14386),
 ('BEVERLY', 1636),
 ('BRIDGEPORT', 3167),
 ('BRIGHTON PARK', 9647),
 ('BURNSIDE', 549),
 ('CALUMET HEIGHTS', 1568),
 ('CHATHAM', 5042),
 ('CHICAGO LAWN', 7086),
 ('CLEARING', 2085),
 ('DOUGLAS', 4670),
 ('DUNNING', 4568),
 ('EAST GARFIELD PARK', 5337),
 ('EAST SIDE', 5305),
 ('EDGEWATER', 4600),
 ('EDISON PARK', 910),
 ('ENGLEWOOD', 6832),
 ('FOREST GLEN', 1431),
 ('FULLER PARK', 531),
 ('GAGE PARK', 9915),
 ('GARFIELD RIDGE', 4552),
 ('GRAND BOULEVARD', 2809),
 ('GREATER GRAND CROSSING', 4051),
 ('HEGEWISCH', 963),
 ('HERMOSA', 3975),
 ('HUMBOLDT PARK', 8620),
 ('HYDE PARK', 1930),
 ('IRVING PARK', 7764),
 ('JEFFERSON PARK', 1755),
 ('KENWOOD', 4287),
 ('LAKE VIEW', 7055),
 ('LINCOLN PARK', 5615),
 ('LINCOLN SQUARE', 4132),
 ('LOGAN SQUARE', 7351),
 ('LOOP', 871),
 ('LOWER WEST SIDE', 7257),
 ('MCKINLEY PARK', 1552),
 ('MONTCLARE', 1317),
 ('MORGAN PARK', 3271),
 ('MOUNT GREENWOOD', 2091),
 ('NEAR NORTH SIDE', 3362),
 ('NEAR SOUTH SIDE', 1378),
 ('NEAR WEST SIDE', 7975),
 ('NEW CITY', 7922),
 ('NORTH CENTER', 7541),
 ('NORTH LAWNDALE', 5146),
 ('NORTH PARK', 4210),
 ('NORWOOD PARK', 6469),
 ('OAKLAND', 140),
 ('OHARE', 786),
 ('PORTAGE PARK', 6954),
 ('PULLMAN', 1620),
 ('RIVERDALE', 1547),
 ('ROGERS PARK', 4068),
 ('ROSELAND', 7020),
 ('SOUTH CHICAGO', 4043),
 ('SOUTH DEERING', 1859),
 ('SOUTH LAWNDALE', 14793),
 ('SOUTH SHORE', 4543),
 ('UPTOWN', 4388),
 ('WASHINGTON HEIGHTS', 4006),
 ('WASHINGTON PARK', 2648),
 ('WEST ELSDON', 3700),
 ('WEST ENGLEWOOD', 5946),
 ('WEST GARFIELD PARK', 2622),
 ('WEST LAWN', 4207),
 ('WEST PULLMAN', 3240),
 ('WEST RIDGE', 8197),
 ('WEST TOWN', 9429),
 ('WOODLAWN', 4206)]

Double-click **here** for a hint

<!--
Verify the exact name of the Enrollment column in the database
Use the SUM() function to add up the Enrollments for each Community Area
-->

Double-click **here** for another hint

<!--
Don't forget to group by the Community Area
-->

Double-click **here** for the solution.

<!-- Solution:

%sql select Community_Area_Name, sum(College_Enrollment) AS TOTAL_ENROLLMENT \
   from CHICAGO_PUBLIC_SCHOOLS_DATA \
   group by Community_Area_Name 

-->

### Problem 9

##### Get the 5 Community Areas with the least total College Enrollment  sorted in ascending order

In [71]:
%sql SELECT * \
    FROM (SELECT `Community Area Name`, SUM(`College Enrollment (number of students)	`) AS TOTAL \
            FROM Schools	\
            GROUP BY `Community Area Name`) AS TOTALES \
    ORDER BY TOTAL \
    LIMIT 5

 * sqlite:///RealWorldData.db
Done.

[('OAKLAND', 140),
 ('FULLER PARK', 531),
 ('BURNSIDE', 549),
 ('OHARE', 786),
 ('LOOP', 871)]

Double-click **here** for a hint

<!--
Order the previous query and limit the number of rows you fetch
-->

Double-click **here** for the solution.

<!-- Solution:

%sql select Community_Area_Name, sum(College_Enrollment) AS TOTAL_ENROLLMENT \
   from CHICAGO_PUBLIC_SCHOOLS_DATA \
   group by Community_Area_Name \
   order by TOTAL_ENROLLMENT asc \
   LIMIT 5 

-->

### Problem 10

##### List 5 schools with lowest safety score.

In [75]:
%sql SELECT `Name of School`, `Safety Score` FROM schools WHERE `Safety Score` > 0 ORDER BY `Safety Score` LIMIT 5

 * sqlite:///RealWorldData.db
Done.

[('Edmond Burke Elementary School', 1.0),
 ("Luke O'Toole Elementary School", 5.0),
 ('George W Tilton Elementary School', 6.0),
 ('Foster Park Elementary School', 11.0),
 ('John Fiske Elementary School', 13.0)]

In [76]:
%sql SELECT `Name of School`, `Safety Score` FROM schools WHERE `Safety Score` != 'None' ORDER BY `Safety Score` LIMIT 5

 * sqlite:///RealWorldData.db
Done.

[('Edmond Burke Elementary School', 1.0),
 ("Luke O'Toole Elementary School", 5.0),
 ('George W Tilton Elementary School', 6.0),
 ('Foster Park Elementary School', 11.0),
 ('John Fiske Elementary School', 13.0)]

Double-click **here** for the solution.

<!-- Solution SQLite:

%sql SELECT name_of_school, safety_score \
FROM CHICAGO_PUBLIC_SCHOOLS_DATA  where safety_score !='None' \
ORDER BY safety_score \
LIMIT 5

-->

### Problem 11

##### Get the hardship index for the community area of the school which has College Enrollment of 4368

In [77]:
df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv")
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")

78

In [78]:
%sql SELECT name,type,length(type) FROM PRAGMA_table_info('CENSUS_DATA')

 * sqlite:///RealWorldData.db
Done.

[('COMMUNITY_AREA_NUMBER', 'REAL', 4),
 ('COMMUNITY_AREA_NAME', 'TEXT', 4),
 ('PERCENT_OF_HOUSING_CROWDED', 'REAL', 4),
 ('PERCENT_HOUSEHOLDS_BELOW_POVERTY', 'REAL', 4),
 ('PERCENT_AGED_16__UNEMPLOYED', 'REAL', 4),
 ('PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA', 'REAL', 4),
 ('PERCENT_AGED_UNDER_18_OR_OVER_64', 'REAL', 4),
 ('PER_CAPITA_INCOME', 'INTEGER', 7),
 ('HARDSHIP_INDEX', 'REAL', 4)]

In [81]:
%sql SELECT S.`Community Area Name`, CD.HARDSHIP_INDEX \
    FROM Schools AS S, CENSUS_DATA AS CD	\
    WHERE S.`Community Area Number` = CD.COMMUNITY_AREA_NUMBER and S.`College Enrollment (number of students)	` = 4368

 * sqlite:///RealWorldData.db
Done.

[('NORTH CENTER', 6.0)]

Double-click **here** for the solution.

<!-- Solution:
NOTE: For this solution to work the CHICAGO_SOCIOECONOMIC_DATA table 
      as created in the last lab of Week 3 should already exist. If the CHICAGO_SOCIOECONOMIC_DATA table does not exists, please execute the following code beforehand.

df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv")
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")


%%sql 
select hardship_index from CENSUS_DATA CD, CHICAGO_PUBLIC_SCHOOLS_DATA CPS 
where CD.community_area_number = CPS.community_area_number 
and college_enrollment = 4368


-->

### Problem 12

##### Get the hardship index for the community area which has the highest value for College Enrollment

In [82]:
%sql SELECT S.`Community Area Name`, CD.HARDSHIP_INDEX \
    FROM Schools AS S, CENSUS_DATA AS CD	\
    WHERE S.`Community Area Number` = CD.COMMUNITY_AREA_NUMBER and S.`College Enrollment (number of students)	` = (SELECT MAX(`College Enrollment (number of students)	`) FROM Schools)

 * sqlite:///RealWorldData.db
Done.

[('NORTH CENTER', 6.0)]

Double-click **here** for the solution.

<!-- Solution:
NOTE: For this solution to work the CHICAGO_SOCIOECONOMIC_DATA table 
      as created in the last lab of Week 3 should already exist. If the CHICAGO_SOCIOECONOMIC_DATA table does not exists, please execute the following code beforehand.

df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv")
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")

%sql select community_area_number, community_area_name, hardship_index from CENSUS_DATA \
   where community_area_number in \
   ( select community_area_number from CHICAGO_PUBLIC_SCHOOLS_DATA order by college_enrollment desc limit 1 )
-->

## Summary

##### In this lab you learned how to work with a real word dataset using SQL and Python. You learned how to query columns with spaces or special characters in their names and with mixed case names. You also used built in database functions and practiced how to sort, limit, and order result sets, as well as used sub-queries and worked with multiple tables.

## Author

<a href="https://www.linkedin.com/in/ravahuja/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Rav Ahuja</a>
<!--
## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                        |
| ----------------- | ------- | ----------------- | ----------------------------------------- |
| 2022-03-04        | 2.2     | Lakshmi Holla     | Made changes in markdown cells |
| 2020-11-27        | 2.1     | Sannareddy Ramesh | Modified data sets and added new problems |
| 2020-08-28        | 2.0     | Lavanya           | Moved lab to course repo in GitLab        |
-->
<hr>

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>